/*
    Barebones create databases 
*/
CREATE DATABASE [OSDS_ETL]
	GO
	USE OSDS_ETL;
	GO
	CREATE SCHEMA IPEDS
	GO
	CREATE SCHEMA CENSUS
	GO
	CREATE SCHEMA CCD
	GO
	CREATE SCHEMA SHARED
	GO
	CREATE SCHEMA IC
	GO

CREATE DATABASE OSDS_RPT
GO
USE OSDS_RPT;
	GO
	CREATE SCHEMA IPEDS
	GO
	CREATE SCHEMA CENSUS
	GO
	CREATE SCHEMA CCD
	GO
	CREATE SCHEMA SHARED
	GO
	CREATE SCHEMA IC

GO
/*REATE DATABASE LOGIN FOR SQL_ALCHEMY USER*/
use master;
CREATE LOGIN [sql_alchemy] WITH PASSWORD=N'sql_alchemy'
	, DEFAULT_DATABASE=[SLDS_ETL]
	, DEFAULT_LANGUAGE=[us_english]
	, CHECK_EXPIRATION=OFF
	, CHECK_POLICY=OFF
GO
/*GRANT ACCESS TO ETL DATABASE*/
USE OSDS_ETL;
    CREATE USER [sql_alchemy] FOR LOGIN [sql_alchemy] WITH DEFAULT_SCHEMA=[dbo]
    GO
	ALTER ROLE db_datareader ADD MEMBER [sql_alchemy]
	GO
	ALTER ROLE db_datawriter ADD MEMBER [sql_alchemy]
	GO
	ALTER ROLE db_owner ADD MEMBER [sql_alchemy]
	GO