/*

Unduplicated 12-month enrollment counts

    (2210104 rows affected) 
	Total execution time: 00:01:02.871
*/
USE OSDS_ETL;

GO
DROP VIEW IPEDS.vw_FactUnduplicatedEnrollment
GO
CREATE VIEW IPEDS.vw_FactUnduplicatedEnrollment AS

	SELECT 
		CAST(BASE.SURVEY_YEAR AS INT) AcademicYr
		, CAST(BASE.UNITID AS INT) UnitID
		, I.StateFIPSCd
		, I.CountyFIPSCd	
		, CAST(BASE.EFFYLEV AS SMALLINT) [EnrollmentLevelFK]
		, EFFYLEV.LookupDesc [EnrollmentLevelDesc]

		--, BASE.LSTUDY --duplicative of EFFYLEV - basically same values

		--, L.LookupCd
		--, L.LookupDesc
		, L.LookupCategory1 [GenderCd]
		, L.LookupCategory2 [IPEDSRaceCd]

		, SUM(BASE.ENROLLMENT) UnduplicatedEnrollment
	
	FROM (
		SELECT DISTINCT
			SURVEY_YEAR
			, UNITID
			, EFFYLEV
			, LSTUDY
			, EFY_CODE
			, CAST(ENROLLMENT AS BIGINT) ENROLLMENT
		FROM 
			(
				/*Base extract - filter out generated totals*/
				SELECT 
					EFY.SURVEY_YEAR
					, EFY.UNITID
					, EFY.EFFYLEV
					, EFY.LSTUDY

					, DVEYAIM, DVEYAIT, DVEYAIW, DVEYAPM, DVEYAPT, DVEYAPW, DVEYBKM, DVEYBKT
					, DVEYBKW, DVEYHSM, DVEYHST, DVEYHSW, DVEYWHM, DVEYWHT, DVEYWHW
	
					, EFY2MORM, EFY2MORT, EFY2MORW, EFYAIANM, EFYAIANT, EFYAIANW, EFYASIAM
					, EFYASIAT, EFYASIAW, EFYBKAAM, EFYBKAAT, EFYBKAAW, EFYHISPM, EFYHISPT
					, EFYHISPW, EFYNHPIM, EFYNHPIT, EFYNHPIW, EFYNRALM, EFYNRALT, EFYNRALW
					, EFYTOTLM, EFYTOTLT, EFYTOTLW, EFYUNKNM, EFYUNKNT, EFYUNKNW, EFYWHITM, EFYWHITT, EFYWHITW
				
					, FYRACE01, FYRACE02, FYRACE03, FYRACE04, FYRACE05, FYRACE06, FYRACE07, FYRACE08
					, FYRACE09, FYRACE10, FYRACE11, FYRACE12, FYRACE13, FYRACE14, FYRACE15, FYRACE16
					, FYRACE17, FYRACE18, FYRACE19, FYRACE20, FYRACE21, FYRACE22, FYRACE23, FYRACE24

				FROM IPEDS.tblEFFY EFY

				WHERE EFY.EFFYLEV NOT IN (1) -- Exclude all students total
					AND EFY.LSTUDY NOT IN (999) --Exclude Generated Total

					--AND UNITID = 214777 -----------------TEST
			) EFY_BASE
			UNPIVOT (
						ENROLLMENT
						FOR EFY_CODE IN 
							(
								DVEYAIM, DVEYAIT, DVEYAIW, DVEYAPM, DVEYAPT, DVEYAPW, DVEYBKM, DVEYBKT
								, DVEYBKW, DVEYHSM, DVEYHST, DVEYHSW, DVEYWHM, DVEYWHT, DVEYWHW
	
								, EFY2MORM, EFY2MORT, EFY2MORW, EFYAIANM, EFYAIANT, EFYAIANW, EFYASIAM
								, EFYASIAT, EFYASIAW, EFYBKAAM, EFYBKAAT, EFYBKAAW, EFYHISPM, EFYHISPT
								, EFYHISPW, EFYNHPIM, EFYNHPIT, EFYNHPIW, EFYNRALM, EFYNRALT, EFYNRALW
								, EFYTOTLM, EFYTOTLT, EFYTOTLW, EFYUNKNM, EFYUNKNT, EFYUNKNW, EFYWHITM, EFYWHITT, EFYWHITW, FYRACE01
	
								, FYRACE02, FYRACE03, FYRACE04, FYRACE05, FYRACE06, FYRACE07, FYRACE08, FYRACE09
								, FYRACE10, FYRACE11, FYRACE12, FYRACE13, FYRACE14, FYRACE15, FYRACE16, FYRACE17
								, FYRACE18, FYRACE19, FYRACE20, FYRACE21, FYRACE22, FYRACE23, FYRACE24

							) 
						) EFY_UNPIVOT
		) BASE
	INNER JOIN IPEDS.vw_DimInstitution I ON BASE.UNITID = I.UnitID
	INNER JOIN SHARED.vw_UniqueLookupList L ON LTRIM(RTRIM(BASE.EFY_CODE)) = L.LookupCd
											AND UPPER(L.LookupName) = 'EFY_CODES'
											AND UPPER(L.LookupCategory1) <> 'T' -- Exclude gender totals
											AND UPPER(L.LookupCategory2) <> 'T' --Exclude race totals
	LEFT JOIN SHARED.vw_UniqueLookupList EFFYLEV ON BASE.EFFYLEV = EFFYLEV.LookupCd AND EFFYLEV.Source = 'IPEDS_EFFY' AND EFFYLEV.LookupName = 'EFFYLEV'
	--LEFT JOIN SHARED.vw_UniqueLookupList LSTUDY ON BASE.LSTUDY = LSTUDY.LookupCd AND LSTUDY.Source = 'IPEDS_EFFY' AND LSTUDY.LookupName = 'LSTUDY' --Duplicative of EFFYLEV - basically same values
	GROUP BY 
		CAST(BASE.SURVEY_YEAR AS INT) 
		, CAST(BASE.UNITID AS INT) 
		, I.StateFIPSCd
		, I.CountyFIPSCd
	
		, BASE.EFFYLEV
		, EFFYLEV.LookupDesc

		--, L.LookupCd
		--, L.LookupDesc
		, L.LookupCategory1
		, L.LookupCategory2

	--ORDER BY UnitID, AcademicYr DESC, 6,8,10

GO
DROP TABLE OSDS_RPT.IPEDS.tblFactUnduplicatedEnrollment
SELECT * INTO OSDS_RPT.IPEDS.tblFactUnduplicatedEnrollment FROM OSDS_ETL.IPEDS.vw_FactUnduplicatedEnrollment
CREATE CLUSTERED COLUMNSTORE INDEX IX_tblFactUnduplicatedEnrollment ON OSDS_RPT.IPEDS.tblFactUnduplicatedEnrollment